version: "2" # specify docker-compose version

# Define the services/containers to be run
services:
  vue-portfolio: # name of the first service
    hostname: vue-portfolio
    restart: unless-stopped
    container_name: vue-portfolio
    build: ./ # specify the directory of the Dockerfile
    labels:
      - traefik.backend=vue-portfolio
      - "traefik.frontend.rule=Host:daton.it,www.daton.it"
      - traefik.docker.network=traefik_proxy
      - traefik.port=80
      - com.docker.compose.project=vue-portfolio
    networks:
      - traefik_proxy

networks:
  traefik_proxy:
    external: true
