declare module "vue-range-component" {
  export const props: {
    show: boolean;
    value: string | number | [] | {};
    min: number;
    max: number;
    step: number;
    width: number | string;
    height: number | string;
    dotSize: number;
    dotWidth: number;
    dotHeight: number;
    stopPropagation: boolean;
    eventType: string;
    realTime: boolean;
    tooltip: string | boolean;
    direction: "horizonyal" | "vertical";
    reverse: boolean;
    disabled: boolean | [];
    piecewiseLabel: boolean;
    piecewise: boolean;
    processDraggable: boolean;
    clickable: boolean;
    fixed: boolean;
    debug: boolean;
    minRange: number;
    maxRange: number;
    tooltipMerge: boolean;
    startAnimation: boolean;
    lazy: boolean;
    enableCross: boolean;
    speed: number;
    useKeyboard: boolean;
    actionsKeyboard: [];
    data: [];
    formatter: string | Function;
    mergeFormatter: string | Function;
    tooltipDir: [] | string;
    tooltipStyle: [] | {} | Function;
    sliderStyle: [] | {} | Function;
    focusStyle: [] | {} | Function;
    disabledStyle: {};
    processStyle: {};
    bgStyle: {};
    piecewiseStyle: {};
    piecewiseActiveStyle: {};
    disabledDotStyle: [] | {} | Function;
    labelStyle: {};
    labelActiveStyle: {};
  };
}
